### ISSUE TITLE
selbal.cv error

### ISSUE THREAD

**Issue by msubirana** [malucalle/selbal#28]
Hi, 

I am trying to use selbal and I got the following error. Any suggestion? Thanks in advance!

```
############################################################### 
 STARTING selbal.cv FUNCTION 
###############################################################

#-------------------------------------------------------------# 
# ZERO REPLACEMENT . . .

Warning in cmultRepl(x, suppress.print = T) :
  Column(s) containing more than 80% zeros/unobserved values were found (check it out using zPatterns).
                    (You can use the z.warning argument to modify the warning threshold).
Error in cmultRepl(x, suppress.print = T) : 
  GBM method: not enough information to compute t hyper-parameter,
                                                probably there are columns with < 2 positive values.
```

**Comment by UVic-omics** [comment]
Hi @msubirana!

First of all thank you for using selbal and my apologies for the dealy in response.

About the error you got when running selbal, it is due to the high amount of zeros in some of your explanatory variables. In order to avoid this error there are two main alternatives:

- The first one is to avoid those variables from the analysis
- The second one is to use those variables as covariates indicating presence (if they are not 0) or absence (if they are 0), recoding them by 1 and 0, respectivelly.

If more than the 80% of the values of a variable is defined by zeros, it may be non-informative for the anallysis. Nevertheless, if you think it is important, we think the second alternative is the best option for your analysis.

**Comment by msubirana** [comment]
Ok! Solved thanks for your support.
